version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    restart: "no"
    command: "true"
    volumes:
      - ./:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    restart: "no"
    volumes:
      - ./:/app
